import os
from datetime import datetime
from typing import Any, Dict, List

from core import __app_name__, __version__


def export_vulnerability_report(
    target_host: str,
    open_findings: List[Dict[str, Any]],
    scan_mode: str,
    ports_scanned: int = 0,
    duration_seconds: float = 0.0,
    output_dir: str = ".",
) -> str:
    """
    Compiles the scan results into a polished Markdown audit report and
    writes it to disk. Returns the path to the written file.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    os.makedirs(output_dir, exist_ok=True)
    report_filename = os.path.join(output_dir, f"nexus_audit_{target_host.replace('.', '_')}.md")

    markdown_buffer = (
        f"# ⚔️ {__app_name__} COMPREHENSIVE VULNERABILITY AUDIT\n\n"
        f"## 📋 CRITICAL ASSESSMENT SUMMARY\n"
        f"- **Audited Target Host/IP**: `{target_host}`\n"
        f"- **Execution Timestamp**: {timestamp}\n"
        f"- **Threat Assessment Mode**: `{scan_mode}`\n"
        f"- **Ports Scanned**: {ports_scanned}\n"
        f"- **Scan Duration**: {duration_seconds:.2f}s\n"
        f"- **Total Exposed Ports Identified**: {len(open_findings)}\n"
        f"- **Generated By**: {__app_name__} v{__version__}\n\n"
        f"----------\n\n"
        f"## 🚨 TARGET EXPOSURE MATRIX\n\n"
    )

    if not open_findings:
        markdown_buffer += (
            "### 🎉 VERDICT: ZERO EXPOSURES DISCOVERED\n"
            "No open attack surfaces identified across the scanned ports.\n"
        )
    else:
        for index, finding in enumerate(open_findings, 1):
            markdown_buffer += (
                f"### {index}. Exposed Interface: Port {finding['port']} ({finding['service']})\n"
                f"- **OWASP Top 10 Category**: `{finding['owasp_category']}`\n"
                f"- **Inferred Weakness**: {finding['vulnerability']}\n"
                f"- **Raw Banner Grabbed**: `{finding['banner_grabbed']}`\n\n"
                f"#### 🛠️ Automated Remediation Strategy\n"
                f"```text\n"
                f"{finding.get('patch', 'No recommendation generated.')}\n"
                f"```\n"
                f"\n----------\n\n"
            )

    markdown_buffer += (
        "\n\n*⚠️ DISCLAIMER: This document was compiled autonomously for authorized "
        "white-hat auditing purposes only. Do not scan systems you do not own or lack "
        "explicit written permission to test.*"
    )

    with open(report_filename, "w", encoding="utf-8") as f:
        f.write(markdown_buffer)

    return report_filename
